# Default initial positions for dynamixel_hexapod's ros2_control fake system

initial_positions:
  joint_1A: 0.0
  joint_1B: 0.0
  joint_1C: 0.0
  joint_2A: 0.0
  joint_2B: 0.0
  joint_2C: 0.0
  joint_3A: 0.0
  joint_3B: 0.0
  joint_3C: 0.0
  joint_4A: 0.0
  joint_4B: 0.0
  joint_4C: 0.0
  joint_5A: 0.0
  joint_5B: 0.0
  joint_5C: 0.0
  joint_6A: 0.0
  joint_6B: 0.0
  joint_6C: 0.0