# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - LEG1_controller
    - LEG2_controller
    - LEG3_controller
    - LEG4_controller
    - LEG5_controller
    - LEG6_controller
    - GROUP1_controller
    - GROUP2_controller

  LEG1_controller:
    type: FollowJointTrajectory
    joints:
      - 1A_joint
      - 1B_joint
      - 1C_joint
  LEG2_controller:
    type: FollowJointTrajectory
    joints:
      - 2A_joint
      - 2B_joint
      - 2C_joint
  LEG3_controller:
    type: FollowJointTrajectory
    joints:
      - 3A_joint
      - 3B_joint
      - 3C_joint
  LEG4_controller:
    type: FollowJointTrajectory
    joints:
      - 4A_joint
      - 4B_joint
      - 4C_joint
  LEG5_controller:
    type: FollowJointTrajectory
    joints:
      - 5A_joint
      - 5B_joint
      - 5C_joint
  LEG6_controller:
    type: FollowJointTrajectory
    joints:
      - 6A_joint
      - 6B_joint
      - 6C_joint
  GROUP1_controller:
    type: FollowJointTrajectory
    joints:
      - 1A_joint
      - 1B_joint
      - 1C_joint
      - 3A_joint
      - 3B_joint
      - 3C_joint
      - 5A_joint
      - 5B_joint
      - 5C_joint
  GROUP2_controller:
    type: FollowJointTrajectory
    joints:
      - 2A_joint
      - 2B_joint
      - 2C_joint
      - 4A_joint
      - 4B_joint
      - 4C_joint
      - 6A_joint
      - 6B_joint
      - 6C_joint