# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - LEG1_controller
    - LEG2_controller
    - LEG3_controller
    - LEG4_controller
    - LEG5_controller
    - LEG6_controller


  LEG1_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1A
      - joint_1B
      - joint_1C
    action_ns: follow_joint_trajectory
  LEG2_controller:
    type: FollowJointTrajectory
    joints:
      - joint_2A
      - joint_2B
      - joint_2C
    action_ns: follow_joint_trajectory
  LEG3_controller:
    type: FollowJointTrajectory
    joints:
      - joint_3A
      - joint_3B
      - joint_3C
    action_ns: follow_joint_trajectory
  LEG4_controller:
    type: FollowJointTrajectory
    joints:
      - joint_4A
      - joint_4B
      - joint_4C
    action_ns: follow_joint_trajectory
  LEG5_controller:
    type: FollowJointTrajectory
    joints:
      - joint_5A
      - joint_5B
      - joint_5C
    action_ns: follow_joint_trajectory
  LEG6_controller:
    type: FollowJointTrajectory
    joints:
      - joint_6A
      - joint_6B
      - joint_6C
    action_ns: follow_joint_trajectory
