# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    LEG1_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    LEG2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    LEG3_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    LEG4_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    LEG5_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    LEG6_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

LEG1_controller:
  ros__parameters:
    joints:
      - joint_1A
      - joint_1B
      - joint_1C
    command_interfaces:
      - position
    state_interfaces:
      - position
  

LEG2_controller:
  ros__parameters:
    joints:
      - joint_2A
      - joint_2B
      - joint_2C
    command_interfaces:
      - position
    state_interfaces:
      - position
   

LEG3_controller:
  ros__parameters:
    joints:
      - joint_3A
      - joint_3B
      - joint_3C
    command_interfaces:
      - position
    state_interfaces:
      - position
     

LEG4_controller:
  ros__parameters:
    joints:
      - joint_4A
      - joint_4B
      - joint_4C
    command_interfaces:
      - position
    state_interfaces:
      - position
     

LEG5_controller:
  ros__parameters:
    joints:
      - joint_5A
      - joint_5B
      - joint_5C
    command_interfaces:
      - position
    state_interfaces:
      - position
    

LEG6_controller:
  ros__parameters:
    joints:
      - joint_6A
      - joint_6B
      - joint_6C
    command_interfaces:
      - position
    state_interfaces:
      - position
    
